#!/bin/bash

# GRAB

HOST_NAME="badger.giseis.alaska.edu"
HOST_DIR="/home/rmodrak/.dropbox"

# grab files from HOST_DIR
if [ -n "$HOST_NAME" ];
then
    rsync -av ${HOST_NAME}:${HOST_DIR}/* .
else
    rsync -av $HOST_DIR/* .
fi

