#!/bin/bash

# GRAB_TGZ

HOST_NAME="badger.giseis.alaska.edu"
HOST_HOME="/home/rmodrak"

# grab files from HOST_FILE
if [ -n "$HOST_NAME" ];
then
    scp -r ${HOST_NAME}:${HOST_HOME}/.dropbox.tgz .
else
    cp -r $HOST_FILE .
fi

# uncompress archive
tar -xzf .dropbox.tgz
mv .dropbox/* .
rm .dropbox.tgz
rmdir .dropbox

