#!/bin/bash

HOST_NAME="badger.giseis.alaska.edu"
HOST_HOME="/home/rmodrak"
ARCHIVE=".dropbox"


# create archive
mkdir $ARCHIVE
for file in "$@"
do
    cp -r $file $ARCHIVE
done
tar -cpzf "${ARCHIVE}.tgz" $ARCHIVE


if [ -n "$HOST_NAME" ];
then
    scp -r "${ARCHIVE}.tgz" "${HOST_NAME}:${HOST_HOME}"
else
    cp -r "${ARCHIVE}.tgz" "$HOST_HOME"
fi


# remove archive
rm -rf $ARCHIVE "${ARCHIVE}.tgz"

